ms_pages/urls.py
""" url patterns for ms pages """
from django.conf.urls import url
from . import views

urlpatterns = [
    #Home page
    url(r'^$', views.home, name='home'),
    url(r'^home_alter$', views.home_alter, name='home_alter'),

    #Forum
    url(r'^forum$', views.forum, name='forum'),
    url(r'^forum/general_discussion$', views.forum_general_discussion, name='forum_general_discussion'),

    url(r'^forum/gms$', views.forum_gms, name='forum_gms'),
    url(r'^forum/itcg$', views.forum_itcg, name='forum_itcg'),
    url(r'^forum/ms2$', views.forum_ms2, name='forum_ms2'),
    url(r'^topics$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name = 'new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)$', views.new_entry, name = 'new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)$', views.edit_entry, name = 'edit_entry'),

    #News
    url(r'^news$', views.news, name='news'),

    #Music
    url(r'^music$', views.music, name='music'),
    url(r'^music/bgms$', views.music_bgms, name='music_bgms'),
    url(r'^music/others$', views.music_others, name='music_others'),
    url(r'^music/others/budapestsymphony$', views.music_others_budapestsymphony, name='music_others_budapestsymphony'),
    url(r'^music/others/itcg$', views.music_others_itcg, name='music_others_itcg'),
    url(r'^music/others/fanmade$', views.music_others_fanmade, name='music_others_fanmade'),


    #Ingame Databases
    url(r'^ingame_db$', views.ingame_db, name='ingame_db'),

    #Classes and Jobs
    url(r'^ingame_db/class&job$', views.ingame_db_classandjob, name='ingame_db_classandjob'),
    #Warrior
    url(r'^ingame_db/class&job/warrior$', views.ingame_db_classandjob_warrior, name='ingame_db_classandjob_warrior'),
    url(r'^ingame_db/class&job/warrior/explorer$', views.ingame_db_classandjob_warrior_explorer, name='ingame_db_classandjob_warrior_explorer'),
    url(r'^ingame_db/class&job/warrior/aran$', views.ingame_db_classandjob_warrior_aran, name='ingame_db_classandjob_warrior_aran'),
    url(r'^ingame_db/class&job/warrior/dawnwarrior$', views.ingame_db_classandjob_warrior_dawnwarrior, name='ingame_db_classandjob_warrior_dawnwarrior'),
    url(r'^ingame_db/class&job/warrior/demonavenger$', views.ingame_db_classandjob_warrior_demonavenger, name='ingame_db_classandjob_warrior_demonavenger'),
    url(r'^ingame_db/class&job/warrior/demonslayer$', views.ingame_db_classandjob_warrior_demonslayer, name='ingame_db_classandjob_warrior_demonslayer'),
    url(r'^ingame_db/class&job/warrior/hayato$', views.ingame_db_classandjob_warrior_hayato, name='ingame_db_classandjob_warrior_hayato'),
    url(r'^ingame_db/class&job/warrior/kaiser$', views.ingame_db_classandjob_warrior_kaiser, name='ingame_db_classandjob_warrior_kaiser'),
    url(r'^ingame_db/class&job/warrior/mihile$', views.ingame_db_classandjob_warrior_mihile, name='ingame_db_classandjob_warrior_mihile'),
    url(r'^ingame_db/class&job/warrior/zero$', views.ingame_db_classandjob_warrior_zero, name='ingame_db_classandjob_warrior_zero'),
    url(r'^ingame_db/class&job/warrior/blaster$', views.ingame_db_classandjob_warrior_blaster, name='ingame_db_classandjob_warrior_blaster'),
    #Magician
    url(r'^ingame_db/class&job/magician$', views.ingame_db_classandjob_magician, name='ingame_db_classandjob_magician'),
    url(r'^ingame_db/class&job/magician/explorer$', views.ingame_db_classandjob_magician_explorer, name='ingame_db_classandjob_magician_explorer'),
    url(r'^ingame_db/class&job/magician/battlemage$', views.ingame_db_classandjob_magician_battlemage, name='ingame_db_classandjob_magician_battlemage'),
    url(r'^ingame_db/class&job/magician/beasttamer$', views.ingame_db_classandjob_magician_beasttamer, name='ingame_db_classandjob_magician_beasttamer'),
    url(r'^ingame_db/class&job/magician/blazewizard$', views.ingame_db_classandjob_magician_blazewizard, name='ingame_db_classandjob_magician_blazewizard'),
    url(r'^ingame_db/class&job/magician/evan$', views.ingame_db_classandjob_magician_evan, name='ingame_db_classandjob_magician_evan'),
    url(r'^ingame_db/class&job/magician/kanna$', views.ingame_db_classandjob_magician_kanna, name='ingame_db_classandjob_magician_kanna'),
    url(r'^ingame_db/class&job/magician/luminous$', views.ingame_db_classandjob_magician_luminous, name='ingame_db_classandjob_magician_luminous'),
    url(r'^ingame_db/class&job/magician/kinesis$', views.ingame_db_classandjob_magician_kinesis, name='ingame_db_classandjob_magician_kinesis'),
    #Bowman
    url(r'^ingame_db/class&job/bowman$', views.ingame_db_classandjob_bowman, name='ingame_db_classandjob_bowman'),
    url(r'^ingame_db/class&job/bowman/explorer$', views.ingame_db_classandjob_bowman_explorer, name='ingame_db_classandjob_bowman_explorer'),
    url(r'^ingame_db/class&job/bowman/wildhunter$', views.ingame_db_classandjob_bowman_wildhunter, name='ingame_db_classandjob_bowman_wildhunter'),
    url(r'^ingame_db/class&job/bowman/windarcher$', views.ingame_db_classandjob_bowman_windarcher, name='ingame_db_classandjob_bowman_windarcher'),
    url(r'^ingame_db/class&job/bowman/mercedes$', views.ingame_db_classandjob_bowman_mercedes, name='ingame_db_classandjob_bowman_mercedes'),
    #Thief
    url(r'^ingame_db/class&job/thief$', views.ingame_db_classandjob_thief, name='ingame_db_classandjob_thief'),
    url(r'^ingame_db/class&job/thief/explorer$', views.ingame_db_classandjob_thief_explorer, name='ingame_db_classandjob_thief_explorer'),
    url(r'^ingame_db/class&job/thief/dualblade$', views.ingame_db_classandjob_thief_dualblade, name='ingame_db_classandjob_thief_dualblade'),
    url(r'^ingame_db/class&job/thief/nightwalker$', views.ingame_db_classandjob_thief_nightwalker, name='ingame_db_classandjob_thief_nightwalker'),
    url(r'^ingame_db/class&job/thief/phantom$', views.ingame_db_classandjob_thief_phantom, name='ingame_db_classandjob_thief_phantom'),
    url(r'^ingame_db/class&job/thief/xenon$', views.ingame_db_classandjob_thief_xenon, name='ingame_db_classandjob_thief_xenon'),
    #Pirate
    url(r'^ingame_db/class&job/pirate$', views.ingame_db_classandjob_pirate, name='ingame_db_classandjob_pirate'),
    url(r'^ingame_db/class&job/pirate/explorer$', views.ingame_db_classandjob_pirate_explorer, name='ingame_db_classandjob_pirate_explorer'),
    url(r'^ingame_db/class&job/pirate/angelicbuster$', views.ingame_db_classandjob_pirate_angelicbuster, name='ingame_db_classandjob_pirate_angelicbuster'),
    url(r'^ingame_db/class&job/pirate/cannoneer$', views.ingame_db_classandjob_pirate_cannoneer, name='ingame_db_classandjob_pirate_cannoneer'),
    url(r'^ingame_db/class&job/pirate/jett$', views.ingame_db_classandjob_pirate_jett, name='ingame_db_classandjob_pirate_jett'),
    url(r'^ingame_db/class&job/pirate/mechanic$', views.ingame_db_classandjob_pirate_mechanic, name='ingame_db_classandjob_pirate_mechanic'),
    url(r'^ingame_db/class&job/pirate/shade$', views.ingame_db_classandjob_pirate_shade, name='ingame_db_classandjob_pirate_shade'),
    url(r'^ingame_db/class&job/pirate/thunderbreaker$', views.ingame_db_classandjob_pirate_thunderbreaker, name='ingame_db_classandjob_pirate_thunderbreaker'),
    #Beginner
    url(r'^ingame_db/class&job/beginner$', views.ingame_db_classandjob_beginner, name='ingame_db_classandjob_beginner'),

    #Items
    url(r'^ingame_db/items$', views.ingame_db_items, name='ingame_db_items'),
    url(r'^ingame_db_items/(?P<item_id>\d+)/$', views.ingame_db_items_details, name='ingame_db_items_details'),

    #Monster
    url(r'^ingame_db/monster$', views.ingame_db_monster, name='ingame_db_monster'),


    #ITCG
    url(r'^itcg$', views.itcg, name='itcg'),
    url(r'^itcg/baseset$', views.itcg_baseset, name='itcg_baseset'),
    url(r'^itcg/baseset/(?P<card_id>\d+)$', views.itcg_baseset_details, name='itcg_baseset_details'),
    url(r'^itcg/omgbosses$', views.itcg_omgbosses, name='itcg_omgbosses'),
    url(r'^itcg/omgbosses/(?P<card_id>\d+)$', views.itcg_omgbosses_details, name='itcg_omgbosses_details'),
    url(r'^itcg/p3ts$', views.itcg_p3ts, name='itcg_p3ts'),
    url(r'^itcg/p3ts/(?P<card_id>\d+)$', views.itcg_p3ts_details, name='itcg_p3ts_details'),
    url(r'^itcg/npcheroes$', views.itcg_npcheroes, name='itcg_npcheroes'),
    url(r'^itcg/npcheroes/(?P<card_id>\d+)$', views.itcg_npcheroes_details, name='itcg_npcheroes_details'),
    url(r'^itcg/beholdzakum$', views.itcg_beholdzakum, name='itcg_beholdzakum'),
    url(r'^itcg/beholdzakum/(?P<card_id>\d+)$', views.itcg_beholdzakum_details, name='itcg_beholdzakum_details'),
    url(r'^itcg/dangersofthedeepsea$', views.itcg_dangersofthedeepsea, name='itcg_dangersofthedeepsea'),
    url(r'^itcg/dangersofthedeepsea/(?P<card_id>\d+)$', views.itcg_dangersofthedeepsea_details, name='itcg_dangersofthedeepsea_details'),


    #Maplestory 2
    url(r'^ms2$', views.ms2, name='ms2'),

    ]

ms_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace = 'users')),
    url(r'', include('ms_pages.urls', namespace='ms_pages')),

]

#if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),

users/urls.py
""" Define URL patterns for users """

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    #login page
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name = 'login'),
    #logout page
    url(r'^logout/$', views.logout_view, name='logout'),
    #Registration page
    url(r'^register/$', views.register, name='register'),

    ]

ms_pages/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """ A topic about maplestory """
    text = models.CharField(max_length=300)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """ represent topic with a string of it's name """
        return self.text

class Entry(models.Model):
    """ Things relate to a topic """
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add= True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """ represent entry with first 50 characters """
        return self.text[:50] + '...'

ms_pages/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

ms_pages/templates/ms_pages/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MapleSnow</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static '/static_dirs/css/style.css' %}">
    <link rel="icon" href="{% static '/static_dirs/images/mapleleaf_001.png' %}">

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default">
      <div class="container">

        <div class="navbar-header">

        </div>

        <div class="row">

        {% if user.is_authenticated %}

          <div class="col-md-9 col-sm-7 col-xs-5">

            <ul id=high1 class="nav navbar-nav">
              <li><a href="{% url 'ms_pages:home' %}">

                MapleSnow
                <img src="{% static '/static_dirs/images/mapleleaf_001.png' %}" alt='' style='height:25px'>
              </a></li>

            </ul>

          </div>



          <div class="col-md-2 col-sm-3 col-xs-4">
            <ul class="nav navbar-nav navbar-right">
            <li><a>Hello, {{ user.username }}.</a></li>
            </ul>
          </div>

          <div class="col-md-1 col-sm-2 col-xs-3">
            <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'users:logout' %}">log out</a><li>
            </ul>
          </div>



          {% else %}

          <div class="col-md-9 col-sm-7 col-xs-6">

            <ul id=high1 class="nav navbar-nav">
              <li><a href="{% url 'ms_pages:home' %}">

                MapleSnow
                <img src="{% static '/static_dirs/images/mapleleaf_001.png' %}" alt='' style='height:25px'>
              </a></li>

            </ul>

          </div>

          <div class="col-md-2 col-sm-3 col-xs-3">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'users:register' %}">register</a></li>
            </ul>
          </div>

          <div class="col-md-1 col-sm-2 col-xs-3">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'users:login' %}">log in</a></li>
            </ul>
          </div>

          {% endif %}

        </div><!--/.nav-collapse -->

      </div>
    </nav>


    <div class="page-header">
      {% block header %}{% endblock header %}
    </div>

    {% block breadcrumb %}{% endblock breadcrumb %}



    <div class='container'>
      <div class="row">
        <!--left_side -->
        <div class="col-md-2 col-sm-2 hidden-xs">
          <div class="list-group">
            <a href="{% url 'ms_pages:home_alter'%}" class='list-group-item color-bg-1'>
              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
              Home
            </a>
            <a href="{% url 'ms_pages:news' %}" class='list-group-item color-bg-2'>News</a>
            <a href="{% url 'ms_pages:forum' %}" class='list-group-item color-bg-2'>Forum</a>
            <a href="{% url 'ms_pages:music' %}" class='list-group-item color-bg-1'>
              <span class="glyphicon glyphicon-music" aria-hidden="true"></span>
              music
            </a>
            <a href="{% url 'ms_pages:music_bgms' %}" class='list-group-item color-bg-2'>Original BGMs</a>
            <a href="{% url 'ms_pages:music_others' %}" class='list-group-item color-bg-2'>Others</a>
            <a href="{% url 'ms_pages:ingame_db' %}" class='list-group-item color-bg-1'>
              <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
              Database
            </a>
            <a href="{% url 'ms_pages:ingame_db_classandjob' %}" class='list-group-item color-bg-2'>Classes & Jobs</a>
            <a href="{% url 'ms_pages:ingame_db_items' %}" class='list-group-item color-bg-2'>Items</a>
            <a href="{% url 'ms_pages:ingame_db_monster' %}" class='list-group-item color-bg-2'>Monsters</a>
            <a href="{% url 'ms_pages:itcg' %}" class='list-group-item color-bg-1'>
              <span class="glyphicon glyphicon-pawn" aria-hidden="true"></span>
              ITCG
            </a>
            <a href="{% url 'ms_pages:itcg_baseset' %}" class='list-group-item color-bg-2'>Set 1: Base Set</a>
            <a href="{% url 'ms_pages:itcg_omgbosses' %}" class='list-group-item color-bg-2'>Set 2: OMG Bosses!</a>
            <a href="{% url 'ms_pages:itcg_p3ts' %}" class='list-group-item color-bg-2'>Set 3: P3ts</a>
            <a href="{% url 'ms_pages:itcg_npcheroes' %}" class='list-group-item color-bg-2'>Set 4: Npc Heroes</a>
            <a href="{% url 'ms_pages:itcg_beholdzakum' %}" class='list-group-item color-bg-2'>Set 5: Behold Zakum</a>
            <a href="{% url 'ms_pages:itcg_dangersofthedeepsea' %}" class='list-group-item color-bg-2'>Set 6: Pirates: Dangers of the Deep Sea</a>
            <a href="{% url 'ms_pages:ms2' %}" class='list-group-item color-bg-1'>
              <span class="glyphicon glyphicon-tree-deciduous" aria-hidden="true"></span>
              Maplestory 2
            </a>
          </div>
        </div>

        <!--middle-->
        <div class="col-md-8 col-sm-8 col-xs-12">
          {% block content %}{% endblock content %}
        </div>

        <!--right_side-->
        <div class="col-md-2 col-sm-2 col-xs-12">
          <div class="list-group">
            <p class='list-group-item color-bg-1'>
              <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
              Contact Info
            </p>
          <!--  <a href="{% url 'ms_pages:topic' 5 %}" class='list-group-item color-bg-2'>Suggestions & Bug Reports Form</a>  -->
            <p class='list-group-item color-bg-2'>Email: sastwdnoz@gmail.com</p>
          </div>

          <!--
          <div class="progress">
            <div class="progress-bar color-bg-1 progress-bar-striped active" style='width:100%'>


            </div>
          </div>
        -->

        </div>
      </div>
    </div>

    <!-- /container -->

  </body>

<br>
<hr>
<br>
  <footer class="footer">
      <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-6">
          <span class="text-muted">
            <p>MapleStory is copyright ©2003-2017 by Nexon corporation. Informations obtained
            from MapleSnow are applies to Nexon's Terms of Use.</p>
            <p>MapleSnow is a not-for-profit website aimed at providing MapleStory
              players the best possible information.</p>
            <br>
            <p>A site by Wenchang Li.</p>
            <p>Contact: sastwdnoz@gmail.com</p>

          </span>
        </div>
        <div class="col-md-3">

        </div>

      </div>
    </footer>

<br>
<br>

</html>

ms_pages/templates/ms_pages/ingame_db_classandjob_bowman_mercedes.html
{% extends 'ms_pages/base.html' %}
{% load staticfiles %}

{% block header %}

<div class="container">
  <h1>Mercedes</h1>
</div>

{% endblock header %}



{% block breadcrumb %}

<section id='breadcrumb'>
  <div class="container">
    <ol class='breadcrumb'>
      <li class='active'><a href="{% url 'ms_pages:home' %}">Home</a></li>
      <li class='active'><a href="{% url 'ms_pages:ingame_db_classandjob' %}">Classes and Jobs</a></li>
      <li class='active'><a href="{% url 'ms_pages:ingame_db_classandjob_bowman' %}">Bowman</a></li>
      <li class='active'><a href="{% url 'ms_pages:ingame_db_classandjob_bowman_mercedes' %}">Mercedes</a></li>
    </ol>
  </div>
</section>

{% endblock breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-md-5">
    <h3>Mercedes Overview:</h3>
    <p>
      Mercedes is one of the Six Heroes who sealed away the Black Mage hundreds of years ago, and is a unique archer. She is also the ruler of the elves, an ancient race native to Maple World. Like the Six Heroes, the elves were encased in ice— the Black Mage's final insult. Awoken after centuries of slumber, Mercedes is determined to free her people from the curse. As an elf, Mercedes is extremely fast and nimble, and is armed with Dual Blowguns and Magic Arrows. Though more vulnerable than average Bowmen, Mercedes is much more mobile, and can even ride a unicorn at level 50.
    </p>
  </div>
  <div class="col-md-4">
    <iframe width="440" height="320" src="https://www.youtube.com/embed/PU5OITZdno8?list=PLdHq6YxjJrMnams_kNB03CwMI_p8Uub9n" frameborder="0" gesture="media" allowfullscreen></iframe>
  </div>

</div>
{% endblock content %}

ms_pages/templates/ms_pages/ingame_db_classandjob_magician.html
{% extends 'ms_pages/base.html' %}
{% load staticfiles %}

{% block header %}
<div class="container">
  <h1>Magician</h1>
</div>
{% endblock header %}

{% block breadcrumb %}
<section id='breadcrumb'>
  <div class="container">
    <ol class='breadcrumb'>
      <li class='active'><a href="{% url 'ms_pages:home' %}">Home</a></li>
      <li class='active'><a href="{% url 'ms_pages:ingame_db_classandjob' %}">Classes and Jobs</a></li>
      <li class='active'><a href="{% url 'ms_pages:ingame_db_classandjob_magician' %}">Magician</a></li>
    </ol>
  </div>
</section>
{% endblock breadcrumb %}


{% block  content %}
<!-- first row -->
<div class="row">
  <a href="{% url 'ms_pages:ingame_db_classandjob_magician_explorer' %}">
    <div class="col-md-4">
      <div class="panel">
        <div class="panel-heading color-bg-1">
          <h3 class='panel-title'>Explorer</h3>
        </div>
        <div class="panel-body color-bg-2">
          <img src="{% static '/static_dirs/images/magician_explorer_001.png' %}" class='img-responsive' alt='magician_explorer_001' style='height:280px'>
        </div>
      </div>
    </div>
  </a>

  <a href="{% url 'ms_pages:ingame_db_classandjob_magician_battlemage' %}">
    <div class="col-md-4">
      <div class="panel">
        <div class="panel-heading color-bg-1">
          <h3 class='panel-title'>Battle Mage</h3>
        </div>
        <div class="panel-body color-bg-2">
          <img src="{% static '/static_dirs/images/magician_battlemage_001.png' %}" class='img-responsive' alt='magician_battlemage_001' style='height:280px'>
        </div>
      </div>
    </div>
  </a>

  <a href="{% url 'ms_pages:ingame_db_classandjob_magician_beasttamer' %}">
    <div class="col-md-4">
      <div class="panel">
        <div class="panel-heading color-bg-1">
          <h3 class='panel-title'>Beast Tamer</h3>
        </div>
        <div class="panel-body color-bg-2">
          <img src="{% static '/static_dirs/images/magician_beasttamer_001.png' %}" class='img-responsive' alt='magician_beasttamer_001' style='height:280px'>
        </div>
      </div>
    </div>
  </a>

</div>


<!-- second row -->
<div class="row">
  <a href="{% url 'ms_pages:ingame_db_classandjob_magician_blazewizard' %}">
    <div class="col-md-4">
      <div class="panel">
        <div class="panel-heading color-bg-1">
          <h3 class='panel-title'>Blaze wizard</h3>
        </div>
        <div class="panel-body color-bg-2">
          <img src="{% static '/static_dirs/images/magician_blazewizard_001.png' %}" class='img-responsive' alt='magician_blazewizard_001' style='height:280px'>
        </div>
      </div>
    </div>
  </a>

  <a href="{% url 'ms_pages:ingame_db_classandjob_magician_evan' %}">
    <div class="col-md-4">
      <div class="panel">
        <div class="panel-heading color-bg-1">
          <h3 class='panel-title'>Evan</h3>
        </div>
        <div class="panel-body color-bg-2">
          <img src="{% static '/static_dirs/images/magician_evan_001.png' %}" class='img-responsive' class='img-responsive' alt='magician_evan_001' style='height:280px'>
        </div>
      </div>
    </div>
  </a>

  <a href="{% url 'ms_pages:ingame_db_classandjob_magician_kanna' %}">
    <div class="col-md-4">
      <div class="panel">
        <div class="panel-heading color-bg-1">
          <h3 class='panel-title'>Kanna</h3>
        </div>
        <div class="panel-body color-bg-2">
          <img src="{% static '/static_dirs/images/magician_kanna_001.png' %}" class='img-responsive' alt='magician_kanna_001' style='height:280px'>
        </div>
      </div>
    </div>
  </a>

</div>


<!-- third row -->
<div class="row">
  <a href="{% url 'ms_pages:ingame_db_classandjob_magician_luminous' %}">
    <div class="col-md-4">
      <div class="panel">
        <div class="panel-heading color-bg-1">
          <h3 class='panel-title'>Luminous</h3>
        </div>
        <div class="panel-body color-bg-2">
          <img src="{% static '/static_dirs/images/magician_luminous_001.png' %}" class='img-responsive' alt='magician_luminous_001' style='height:280px'>
        </div>
      </div>
    </div>
  </a>

  <a href="{% url 'ms_pages:ingame_db_classandjob_magician_kinesis' %}">
    <div class="col-md-4">
      <div class="panel">
        <div class="panel-heading color-bg-1">
          <h3 class='panel-title'>Kinesis</h3>
        </div>
        <div class="panel-body color-bg-2">
          <img src="{% static '/static_dirs/images/magician_kinesis_001.png' %}" class='img-responsive' alt='magician_kinesis_001' style='height:280px'>
        </div>
      </div>
    </div>
  </a>

</div>




{% endblock content %}

ms_pages/templates/ms_pages/ingame_db_classandjob_pirate_cannoneer.html
{% extends 'ms_pages/base.html' %}
{% load staticfiles %}

{% block header %}

<div class="container">
  <h1>Cannoneer</h1>
</div>

{% endblock header %}



{% block breadcrumb %}

<section id='breadcrumb'>
  <div class="container">
    <ol class='breadcrumb'>
      <li class='active'><a href="{% url 'ms_pages:home' %}">Home</a></li>
      <li class='active'><a href="{% url 'ms_pages:ingame_db_classandjob' %}">Classes and Jobs</a></li>
      <li class='active'><a href="{% url 'ms_pages:ingame_db_classandjob_pirate' %}">Pirate</a></li>
      <li class='active'><a href="{% url 'ms_pages:ingame_db_classandjob_pirate_cannoneer' %}">Cannoneer</a></li>
    </ol>
  </div>
</section>

{% endblock breadcrumb %}

{% block content %}

<div class="row">
  <div class="col-md-5">
    <h3>Cannoneer Overview:</h3>
    <p>
      The Cannoneer wields a deadly hand cannon forged by the Nautilus’ resident inventor, Cutter. A playful monkey the Cannoneer befriended on Coco Island provides attack support. The Cannoneer's titular weapon deals massive damage and has a wide attack range. In addition dealing powerful hits, the Cannoneer can use his Pirate Blessing skill to buff other characters on the same account. And c'mon... who doesn't want a monkey for a best friend?
    </p>
  </div>
  <div class="col-md-4">
    <iframe width="440" height="320" src="https://www.youtube.com/embed/4DENXeeaz1Q?list=PLdHq6YxjJrMnams_kNB03CwMI_p8Uub9n" frameborder="0" gesture="media" allowfullscreen></iframe>
  </div>

</div>
{% endblock content %}